# Generated by Django 3.2.6 on 2021-10-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetHubApp', '0002_auto_20211019_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
