# Generated by Django 3.2.6 on 2021-10-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NetHubApp', '0003_post_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybookmark', to='NetHubApp.post'),
        ),
    ]
