# Generated by Django 3.2.6 on 2021-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetHubApp', '0004_auto_20211030_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(related_name='mybookmarks', to='NetHubApp.Post'),
        ),
    ]
