# Generated by Django 3.2.6 on 2022-01-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetHubApp', '0007_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
